<?php 

/****************************************************************
 *
 *  Copyright 2011 The President and Fellows of Harvard College
 *  Copyright 2011 Modo Labs Inc.
 *
 *****************************************************************/

/**
 * Implements hook_theme().
 */
function youtube_id_theme() {
  $temp = image_theme();
  return array(
    'youtube_id_formatter' => $temp['image_formatter'],
  );
}

/**
 * Implements hook_field_formatter_info().
 */
function youtube_id_field_formatter_info() {
  return array(
    'youtube_id' => array(
      'label' => t('YouTube iframe'),
      'field types' => array('text'),
      'settings' => array(
        'iframe_width' => 640,
        'iframe_height' => 480,
      ),
    ),
  );
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function youtube_id_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];

  return array(
    'iframe_width' => array(
      '#title' => t('iframe width'),
      '#type' => 'textfield',
      '#size' => 5,
      '#default_value' => $settings['iframe_width'],
      '#element_validate' => array('_element_validate_integer_positive'),
      '#required' => TRUE,
    ),
    'iframe_height' => array(
      '#title' => t('iframe height'),
      '#type' => 'textfield',
      '#size' => 5,
      '#default_value' => $settings['iframe_height'],
      '#element_validate' => array('_element_validate_integer_positive'),
      '#required' => TRUE,
    ),
  );
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function youtube_id_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];

  return t('iframe size') . ': ' . $settings['iframe_width'] . 'x' . $settings['iframe_height'];
}

/**
 * Implements hook_field_formatter_view().
 */
function youtube_id_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  
  foreach ($items as $delta => $item) {
    $output = _text_sanitize($instance, $langcode, $item, 'value');
    $element[$delta] = array(
      '#markup' => '<iframe width="' . $display['settings']['iframe_width'] . 
        '" height="' . $display['settings']['iframe_height'] . 
        '" src="http://www.youtube.com/embed/' . $output . '" frameborder="0"></iframe>',
    );
  }

  return $element;
}
